#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

use Symfony\Component\Console\Input\ArgvInput;

$status = $app->handleCommand(new ArgvInput);

exit($status);
