FROM liquibase/liquibase:4.27

# MySQL JDBC driver required by Liquibase at runtime.
ADD --chown=liquibase:liquibase --chmod=644 https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar /liquibase/lib/mysql-connector-j-8.4.0.jar
